version: '3.8'

services:

  eureka:
    build:
      context: ./Eureka
    ports:
      - "8761:8761"
    networks:
      - kafka-net

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-net

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "vue:1:1"
    networks:
      - kafka-net
    depends_on:
      - zookeeper

  gateway:
    build:
      context: ./Gateway
    ports:
      - "8101:8101"
    networks:
      - kafka-net
    depends_on:
      - eureka
      
      

  vue:
    build:
      context: ./Vue
    ports:
      - "8103:8103"
    networks:
      - kafka-net
    depends_on:
      - eureka
      
  consumer:
    build:
      context: ./Consumer
    ports:
      - "8105:8105"
    networks:
      - kafka-net
    depends_on:
      - kafka

  saga:
    build:
      context: ./Saga
    ports:
      - "8100:8100"
    networks:
      - kafka-net
    depends_on:
      - eureka

  centro:
    build:
      context: ./Centro
    ports:
      - "8090:8090"
    networks:
      - kafka-net
    depends_on:
      - eureka

  marcacao:
    build:
      context: ./Marcacao
    ports:
      - "8091:8091"
    networks:
      - kafka-net
    depends_on:
      - eureka

  utilizador:
    build:
      context: ./Utilizador
    ports:
      - "8092:8092"
    networks:
      - kafka-net
    depends_on:
      - eureka

  vacina:
    build:
      context: ./Vacina
    ports:
      - "8093:8093"
    networks:
      - kafka-net
    depends_on:
      - eureka

networks:
  kafka-net:
    driver: bridge

